# Generated by Django 4.2.7 on 2024-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
